# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js s3 sync

on:
  push:
    branches: [master, production]

jobs:
  build-and-deploy-s3:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: |
          cat <<EOF > ./src/secrets.js
          const secrets = {
            bingKey: '${{ secrets.BING_KEY }}',
            thunderforestKey: '${{ secrets.THUNDERFOREST_KEY }}',
            sentryDSN: '${{ secrets.SENTRY_DSN }}',
            mapillary4: '${{ secrets.MAPILLARY_KEY}}',
            flickr: '${{ secrets.FLICKER_KEY}}',
            google: '${{ secrets.GOOGLE_KEY}}',
            mapyCz: '${{ secrets.MAPYCZ_KEY}}'
          };

          export default secrets;
          EOF
      - run: yarn run test
        env:
          CI: true   
      - run: NODE_ENV=production yarn run build --if-present
      - name: Set S3 Bucket
        id: set_s3_bucket
        run: |
          if [[ "${{ steps.extract_branch.outputs.branch }}" == "production" ]]; then
            echo "BUCKET_NAME=www.track.guide" >> "$GITHUB_OUTPUT"
            #echo "::set-output name=bucket::www.track.guide"
          else
            echo "BUCKET_NAME=beta.track.guide" >> "$GITHUB_OUTPUT"
            #echo "::set-output name=bucket::beta.track.guide"
          fi
      - name: s3 sync
        uses: yalamber/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ steps.set_s3_bucket.outputs.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: 'ap-southeast-2'
          SOURCE_DIR: 'build'